apiVersion: v2
name: moat-stack
description: Umbrella chart that installs the Moat dataplane together with the Moat operator
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: moat
    version: 0.1.0
    repository: "file://charts/moat"
  - name: valkey
    version: 0.7.7
    repository: https://valkey.io/valkey-helm/
  - name: clamav
    version: 1.6.82
    repository: oci://registry.gitlab.com/xrow-public/helm-clamav/charts
maintainers:
  - name: Arxignis
    email: support@arxignis.com


