name: Moat Controller Build
on:
  pull_request:
      branches:
        - main
      paths:
        - moat-operator/**
        - .github/workflows/build-controller.yaml

jobs:
  build-amd64:
    name: Build amd64
    runs-on: ubicloud-standard-4-ubuntu-2404
    strategy:
      matrix:
        go-version: [ '1.24', '1.25' ]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: moat-operator/go.sum
      - name: Display Go version
        run: go version
      - name: Run tests
        run: |
          cd moat-operator
          go mod tidy
          go test -v


  build-arm64:
    name: Build arm64
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        go-version: [ '1.24', '1.25' ]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: moat-operator/go.sum
      - name: Display Go version
        run: go version
      - name: Run tests
        run: |
          cd moat-operator
          go mod tidy
          go test -v
